using System;
using System.Linq;
using System.Net;
using System.Threading.Tasks;

using Ventura.Interfaces;

using Newtonsoft.Json.Linq;

namespace Ventura.Accumulator.EntropyExtractors
{
    /// <summary>
    /// Makes a REST call to an API provided by the  Australian National University (ANU), 
    /// to retrieve numbers generated by measuring the quantum fluctuations of a vacuum,
    /// which quantum mechanical theory predicts will be random.
    /// For more see: http://qrng.anu.edu.au/API/api-demo.php
    /// </summary>
    public class RemoteQuantumRngExtractor : EntropyExtractorBase, IEntropyExtractor
    {
        public RemoteQuantumRngExtractor(int sourceNumber) : base(sourceNumber)
        {
        }

        protected override Task<byte[]> ExtractEntropicData()
        {
            Func<byte[]> extraction = () =>
            {
                using (WebClient wc = new WebClient())
                {
                    var jsonResponse = wc.DownloadString("https://qrng.anu.edu.au/API/jsonI.php?length=30&type=uint8");
                    var jObject = JObject.Parse(jsonResponse);

                    var tokens = jObject["data"].Children().ToList();
                    byte[] result = new byte[30];
                    int i = 0;

                    foreach (var token in tokens)
                    {
                        byte part = token.ToObject<byte>();
                        result[i] = part;
                    }

                    return result;
                }
            };

            return Task.Run(extraction);
        }
    }
}