using System;
using System.Collections.Generic;
using System.Text;

namespace Ventura
{
    public class Constants
    {
        /// <summary>
        /// 256-bit key size
        /// </summary>
        public const int KeyBlockSize = 32; 

        /// <summary>
        /// Size of each cipher block generated by the encryptor
        /// 128 bits according to spec
        /// </summary>
        public const int CipherBlockSize = 16; 

        /// <summary>
        /// Maximum aamount of pseudorandom data generated
        /// before the state key changes
        /// </summary>
        public const int MaximumRequestSizeForStateKey = 1048576;

        /// <summary>
        /// Maximum anount of entropy data in bytes
        /// </summary>
        public const int MaximumEventSize = 32; 

        public const int MaximumNumberOfSources = 255;
        public const int MaximumNumberOfPools = 32;
    }
}
